### ISSUE TITLE
Unable to bind IPC socket

### ISSUE THREAD

**Issue by ktfth** [penumbra23/pura#4]
After compile pura on my machine I have that message related to not bind to IPC socket... how can i solve that?

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

rustc 1.58.1 (db9d1b20b 2022-01-20)

pura create hello-world-node --bundle /home/kaique/war/runc/ --console-socket /tmp/socket
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { msg: "unable to bind IPC socket", err_type: Runtime }', src/main.rs:76:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by penumbra23** [comment]
Hi @ktfth ! Thanks for raising the issue. I'll come back to you once I check it.

**Comment by penumbra23** [comment]
Could you try to run it via Docker? The README.md file has instructions how to integrate it with the Docker daemon.

**Comment by ktfth** [comment]
@penumbra23 all working with pura as runtime, and a PR created to the latest usage of docker. https://github.com/penumbra23/pura/pull/5

**Comment by penumbra23** [comment]
Also, this doesn't solve the issue of running pura as a standalone binary. Need to investigate it more! Thanks for your effort, feel free to continue the good work on this project 👍

**Comment by penumbra23** [comment]
@ktfth Thanks for your effort! You can merge the PR!
Still going to investigate why the binary mode crashes.
